#ifndef WIDGETPLUGIN_GLOBAL_H
#define WIDGETPLUGIN_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(WIDGETPLUGIN_LIBRARY)
#  define PLUGINWIDGETSHARED_EXPORT Q_DECL_EXPORT
#else
#  define WIDGETPLUGINSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // WIDGETPLUGIN_GLOBAL_H
