#ifndef MYSHARELIBRARY_GLOBAL_H
#define MYSHARELIBRARY_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(MYSHARELIBRARY_LIBRARY)
#  define MYSHARELIBRARYSHARED_EXPORT Q_DECL_EXPORT
#else
#  define MYSHARELIBRARYSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // MYSHARELIBRARY_GLOBAL_H
